server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    mysqldsn: root:abc123456@tcp(127.0.0.1:3306)/xa_user?charset=utf8mb4&parseTime=True&loc=Local
    pgsqldsn: host=localhost user=postgres password=abc123456 dbname=xa_user port=9920 sslmode=disable TimeZone=Asia/Shanghai
    dtmServer:
      host: http://localhost
      port: 8082
      busiApi: /api/busi_start
